language: c

install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update
  - sudo apt-get install -y build-essential git gcc-arm-none-eabi

script:
  - make -C vendor/libopencm3
  - make
  - make -C firmware
  - make -C bootloader
  - make -C demo
